# Generated by Django 3.2.6 on 2021-08-26 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('admin_id', models.AutoField(db_column='adminID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'administrator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(db_column='classID', primary_key=True, serialize=False)),
                ('weekday', models.CharField(db_column='weekDay', max_length=9)),
                ('date', models.DateField(blank=True, null=True)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('class_status', models.CharField(choices=[('L', 'Late'), ('C', 'Cancelled'), ('O', 'Ongoing')], db_column='classStatus', max_length=1)),
            ],
            options={
                'db_table': 'class',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(db_column='courseCode', max_length=6, primary_key=True, serialize=False)),
                ('course_name', models.CharField(blank=True, db_column='courseName', max_length=80, null=True)),
                ('year_offered', models.IntegerField(db_column='yearOffered')),
            ],
            options={
                'db_table': 'course',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(db_column='departmentID', primary_key=True, serialize=False)),
                ('dept_name', models.CharField(blank=True, db_column='deptName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'department',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.AutoField(db_column='facultyID', primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(blank=True, db_column='facultyName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'faculty',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('staff_num', models.IntegerField(db_column='staffNum', primary_key=True, serialize=False)),
                ('office_nr', models.CharField(blank=True, db_column='officeNr', max_length=30, null=True)),
                ('phone_nr', models.CharField(blank=True, db_column='phoneNr', max_length=20, null=True)),
                ('course_course_code', models.ForeignKey(db_column='course_courseCode', on_delete=django.db.models.deletion.CASCADE, to='accounts.course')),
                ('department_department_id', models.ForeignKey(db_column='department_departmentID', on_delete=django.db.models.deletion.CASCADE, to='accounts.department')),
            ],
            options={
                'db_table': 'lecturer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.AutoField(db_column='venueID', primary_key=True, serialize=False)),
                ('building', models.IntegerField()),
                ('class_nr', models.CharField(db_column='classNr', max_length=5)),
                ('class_class_id', models.ForeignKey(db_column='class_classID', on_delete=django.db.models.deletion.CASCADE, to='accounts.class')),
            ],
            options={
                'db_table': 'venue',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_profile_id', models.AutoField(db_column='user_profileID', primary_key=True, serialize=False)),
                ('initials', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(blank=True, choices=[('Dr', 'Dr'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms')], max_length=3, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sub_code', models.CharField(db_column='subCode', max_length=7, primary_key=True, serialize=False)),
                ('sub_name', models.CharField(blank=True, max_length=80, null=True)),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('lecturer_staff_num', models.ForeignKey(db_column='lecturer_staffNum', on_delete=django.db.models.deletion.CASCADE, to='accounts.lecturer')),
            ],
            options={
                'db_table': 'subject',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stud_num', models.IntegerField(db_column='studNum', primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('bus_reg', models.IntegerField(db_column='busReg')),
                ('t_cs', models.IntegerField(db_column='T_Cs')),
                ('course_course_code', models.ForeignKey(db_column='course_courseCode', on_delete=django.db.models.deletion.CASCADE, to='accounts.course')),
                ('user_profile_user_profile_id', models.ForeignKey(db_column='user_profile_user_profileID', on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
            options={
                'db_table': 'student',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='lecturer',
            name='user_profile_user_profile_id',
            field=models.ForeignKey(db_column='user_profile_user_profileID', on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.AutoField(db_column='enrollmentID', primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('current_semester', models.IntegerField(db_column='currentSemester')),
                ('course_course_code', models.ForeignKey(db_column='course_courseCode', on_delete=django.db.models.deletion.CASCADE, to='accounts.course')),
                ('subject_sub_code', models.ForeignKey(db_column='subject_subCode', on_delete=django.db.models.deletion.CASCADE, to='accounts.subject')),
            ],
            options={
                'db_table': 'enrollment',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='department',
            name='faculty_faculty_id',
            field=models.ForeignKey(db_column='faculty_facultyID', on_delete=django.db.models.deletion.CASCADE, to='accounts.faculty'),
        ),
        migrations.AddField(
            model_name='course',
            name='department_department_id',
            field=models.ForeignKey(db_column='department_departmentID', on_delete=django.db.models.deletion.CASCADE, to='accounts.department'),
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('consultation_id', models.AutoField(db_column='consultationID', primary_key=True, serialize=False)),
                ('weekday', models.CharField(blank=True, db_column='weekDay', max_length=9, null=True)),
                ('start', models.TimeField()),
                ('end', models.TimeField(blank=True, null=True)),
                ('book_consultation', models.IntegerField(choices=[('Yes', 'Yes'), ('Cancel', 'Cancel')], db_column='bookConsultation')),
                ('topic', models.CharField(max_length=500)),
                ('consultation_status', models.CharField(blank=True, choices=[('A', 'Available'), ('U', 'Unavailable'), ('O', 'Out')], db_column='consultationStatus', max_length=1, null=True)),
                ('lecturer_staff_num', models.ForeignKey(db_column='lecturer_staffNum', on_delete=django.db.models.deletion.CASCADE, to='accounts.lecturer')),
                ('student_stud_num', models.ForeignKey(db_column='student_studNum', on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('subject_sub_code', models.ForeignKey(db_column='subject_subCode', on_delete=django.db.models.deletion.CASCADE, to='accounts.subject')),
            ],
            options={
                'db_table': 'consultation',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='class',
            name='lecturer_staff_num',
            field=models.ForeignKey(db_column='lecturer_staffNum', on_delete=django.db.models.deletion.CASCADE, to='accounts.lecturer'),
        ),
        migrations.AddField(
            model_name='class',
            name='subject_sub_code',
            field=models.ForeignKey(db_column='subject_subCode', on_delete=django.db.models.deletion.CASCADE, to='accounts.subject'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(db_column='attendanceID', primary_key=True, serialize=False)),
                ('class_class_id', models.ForeignKey(db_column='class_classID', on_delete=django.db.models.deletion.CASCADE, to='accounts.class')),
                ('student_stud_num', models.ForeignKey(db_column='student_studNum', on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'db_table': 'attendance',
                'managed': True,
            },
        ),
    ]
