# Generated by Django 3.2.6 on 2021-09-01 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210902_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='date',
        ),
    ]
