# Generated by Django 3.2.6 on 2021-09-02 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_class_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='consultation',
            name='book_consultation',
            field=models.IntegerField(choices=[('1', 'Yes'), ('0', 'Cancel')], db_column='bookConsultation'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='subject_sub_code',
            field=models.ForeignKey(db_column='subject_subCode', on_delete=django.db.models.deletion.CASCADE, to='accounts.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='t_cs',
            field=models.IntegerField(db_column='T&Cs'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub_name',
            field=models.CharField(blank=True, db_column='subName', max_length=80, null=True),
        ),
    ]
