# Generated by Django 3.2.6 on 2021-09-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210902_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='book_consultation',
            field=models.IntegerField(choices=[('Y', 'Yes'), ('C', 'Cancel')], db_column='bookConsultation'),
        ),
    ]
